//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yastrebov_Autoservice
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Service
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string MainImagePath { get; set; }
        public int DurationInSeconds { get; set; }
        public decimal Cost { get; set; }
        public Nullable<double> Discount { get; set; }
        public int DiscountInt
        {
            get
            {
                if (this.Discount != null)
                    return Convert.ToInt32(this.Discount * 100);
                else return 0;
            }
            set
            {
                this.Discount = Convert.ToDouble(value)/100;
            }
        }
        public string Description { get; set; }

        public string OldCost
        {
            get
            {
                if (Discount > 0)
                {
                    return Cost.ToString();
                }
                else
                {
                    return "";
                }
            }
        }

        public decimal NewCost
        {
            get
            {
                if (Discount > 0)
                {
                    return ((decimal)Cost - (decimal)Cost * (decimal)DiscountInt/100);
                }
                else
                {
                    return (decimal)Cost;
                }
            }
        }

        public SolidColorBrush FonStyle
        {
            get
            {
                if (Discount > 0)
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("LightGreen");
                }
                else
                {
                    return (SolidColorBrush)new BrushConverter().ConvertFromString("White");
                }
            }
        }
    }
}
